apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cicd-acme
spec:
  encryptedData:
    token: AgC4aNKpnoysEYDGtimv/KTHY/9kuzKtyUREcVdPjztaV1yhSbR4X4k56I/lu+3xl/TTn9LHjYV68qzqqt2xoDEIyDXfCe4lA130lWY0XLwLV+hOPd0RdJxA4Qpht7CK8vXm3KC7A488bFkgBzAWuoVzjVakVan/jy/MHSdbsIw/CVZynkHGf0y8X+DUH/R8oP8Fh/+h8UEAZoPc7ttHPKirZOqmYjQpQjwvMTk7DDRf+kpsGEkPMRbY40eF2eihrfW/MmaoRIm8TNWuAQgF+XUZeuOXXSt6H3k1m1i77+2Uuep6JhrKCYhci/VAb/v33TqF0bzk3aqYDeJiuG7VEhjoY6KxjWIGvlLObv779zfQdum8ybEG+Xl5yjzraWeYEthPYi5aGxF0MJ+s9AK/8gZ0MnwJ3AhhJklGRZM728Bu8kWJ7fxCjkDpAVv834lXuOyZLgmwLZ5DLPshIpGHBRO2dl5hDipTkZt6Ngyxb7G+YAoC8aho0cvQoS73I3O81G46hP0kmHWyxnl8xhEat0oMUhcn3N2tLsOEJ2EpAYzxXEu+bMb1F6Bko6fiG+P0ezOCyX6olw7j7ng1k0g+KVRBxdz9YGNh4uFmK/X0vI6FV7tAXot7RdQrN0kFulcXgWdd/LVQ3VkHWtqYCN7/JvT9xF/61/ZinTHevrn/gqV4c90J2we1klikcTHz9pnUX+rpFsDzP6ZSxohYeghKL2VmwiTflHi2BO1iV8XIUW33V0Mu7KZzE2cU
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      labels:
        created-by: pipeline
      name: cicd-acme

