apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cicd-acme
spec:
  encryptedData:
    token: AgADPuXGDffdgXiZ31hukBifXxW8Jrkv7VbxN3IkE1pNAUTIxHe7nGAD5RaN/sIn2Oe4ASiGP0EyXEGRHJBtS3Lx/V4AHy928zi30fvu3fS7sWiim82Da8nAK1Y9lMeRWB8jh/WNIHIhLYjDryWMQUMjZDMQQ324Ij0Epw6r4bgekqkcCS1dfY7KZr6LfOzCnCyaDwXH0aYo6s59NqilBTvHgYx3Ap2HKjGlKtafEycfhyWA3xBfgQMcTUGae7cfnJxQhPBHOxcPokwabwIxjc1h3Q/0FKwqFe+ECMgkSwTjqzKnTOASuHHH6gzSRCnq4oV+IAjE7ZuowUWf7WyeSUZ+FFmRsSF/dDiDrl5TbCIz+X1xoYTWTX3gHdwKbqjGHxU3uIxublG5Tt6pkuWeEhyRq3+dCjaHE5wmBUZtqa0x1vOLx2AOd7DPeIp3I74ORcHvs1Xddy+lXgjueJAWx4oLIF1B07d1+ABvYZkEkcSDwykWFtVFrbj45O9IYpWyUWaN/+mTbx2jI+FdY3coe9MApn88E2xk3bz2unsI5+rJcRbcWWVlwkPr4uMyg+PnUAC6U4IbBFa55DNBbylrpclCb1kLII6BdTAfxP4unxafQfHzc2Y4rXp6HykbIXbc6f8z1PPwpdnWzQnLr7qKwKZAzWBGC6T2AXQ0kWBDWTWXRGQxQ/LnHDVmDG6odaMHdq9DR4JCWzfJnd5WI2igRJrykDKKV8S0UOQ9k7IG0BhFMOIGaJ+Ygvv4
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      labels:
        created-by: pipeline
      name: cicd-acme

