apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cicd-acme
spec:
  encryptedData:
    token: AgCqo+Wtw8XJMrHCMJSckUeDtT2TSvboLHgwZVSHZ3J2IzIQjgUqV6LzU5QYJc2YiaX72hoB8bg2YK5kiySh9NUe7NJFzkcPhS6ZZRZ0+b6jpIMQM+W1cDea5LQ9GEvvJ9swmUgKV+FNPE7nsn6OjI8tCVwzP66xLsnH3imYgxbUIMIa/HoDIx0U+RyXWZ1fR6IyEjoFTvcBvOgSSDonzBsx9+XAC0iDSK0Vne8clFp6uKhQ/f14/vqWEZG9AWFRhsBfIb+52Pd9OSTnKSBR6Ymddbqk0A85by5ol4To9FLmT77sPLpOx8TfPJRmHtZ61Me0HLA2mWAfSMKnMZLrnME73neqWfaFyA7OeZZS2gyDg0AWcYG3qfKhE20V62TAlZjyFALYJf0SQktrw7mnXUoRhXLuhpf4c4FjW2Mzp3AwR6f8eZHkDyTS6CwpghkJR+bc5gJN6pu+GFG7CRNjLL07l+4Q6DAyaIEqrKSgwGhI9z5A8jIjlKU2RrR9A6KoSMVPvCAkfl2UkMK4j/SfajUf19zjUjNkeCxjcALw+C4EiZWPYjb9eIuDVTrnguaRWwSs4tt/s6rdws8lJvcWCzfhVxUbkei0jPK4rck3d0i37q6JziwW4bibkC0sJl8rG8XfXH3Iw6DouPmEV1Ijt5JaFfUwNmH1k+jJeAuv14EMmCj07eEor11bDOWV35DSBBIG8Y0pq7IW81lAQDySLGULAePXtmjL6yTqosi8F6KAYP5O1Os6BNJ3
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      labels:
        created-by: pipeline
      name: cicd-acme

