apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cicd-acme
spec:
  encryptedData:
    token: AgBRUuYmZtB/ZY7UAVjJ5XMTWaxTcqz9F9b3c+VHhdi2VHkwJN9rINKnXjUf/Jfu0wmx9qr/hSQ/NPeiUiAeYvN2ltGJIRfAQz831Vi1uO+cC3GGXrQZ873d4cQ/IF2Ok9hj2AlXefbOQce6+QeYU72nczV0gyv3Off89SGdET2Q5MDs8C1knjAU0/9iVCwAIIuhG/kxJNtBFUAR3eOHwZn6g6d5nsJG3IprotlC8r8qFNefz7wWPnhhkDVU/5ODc1IdMu1ghIB75v/jMdOfo4K1bLqpcSfmYPxfmge5ld4RRQj63eP8EWSkVF7+jkKLxwWyV2S6Xdo0QR6Al+OxAW5e8e1kITqvMALUFzVx4oHcHjgA4Y+ocHfzOmIiqXeSsd3tgLO3p9kzxcMKZ8dIlYb1PZ8vAgsz//uSbjZtV+sSWAd6CUfpAOxZ/2eDeT0mVEXa6m8bk4mChdeNX3U46BMIYFwxg2QiDTweXqY4DbUpKf/gCfmc73zRDdhv7C0qQG2D8VRoms7EGUs2fH6J5WcvuTEHRL+lykRibq1z6sZTt/SCkuBRZb25WYOmhBG1xMwFWWF4Qce8KKxX25qYtSB71aRHAMvs9wWftN1B/h7htKCwCoUCYnNDbIOV23Q4ffXSDjmEBfgsHLkOzQalZz29k63Bui4WwZR1M3x3M2Qzw+dCzLo6qb79ZsFGPHzez2a9xJfALtRd5wkgfBnq7TUaXr2hLID/W0gdqs2KBF7etxNle77RGCtM
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      labels:
        created-by: pipeline
      name: cicd-acme

