apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationServer
metadata:
  name: create-customer-details-rest
spec:
  designerFlowsOperationMode: disabled
  license:
    accept: true
    license: L-KSBM-C37J2R
    use: CloudPakForIntegrationNonProduction
  replicas: 1
  router:
    timeout: 120s
  service:
    endpointType: http
  useCommonServices: true
  version: 12.0.1.0-r3
  adminServerSecure: true
  pod:
    containers:
      runtime:
        image: image-registry.openshift-image-registry.svc:5000/ci/create-customer-details-rest:5d447b0eaf19b9fd8dcca5b7f1bd2b73e40fa97c
        imagePullPolicy: Always
  configurations:
    - create-customer-serverconf.yaml
    - create-customer-policy
