apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
 name: prod-ref-devsops
spec:
 secretName: prod-ref-devsops-tls-key-pair
 isCA: true
 issuerRef:
   name: prod-ref-ss
   kind: Issuer
 commonName: appdomain.cloud
 subject:
  countries:
    - UK
  provinces:
    - London
  localities:
    - London
  organizations:
    - IBM
  organizationalUnits:
    - Assets and Architecture, DevOps
 dnsNames:
 - "*.itzroks-5500059ths-bwukw7-6ccd7f378ae819553d37d5f2ee142bd6-0000.eu-gb.containers.appdomain.cloud"
