apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: ibm-entitlement-key
spec:
  encryptedData:
    .dockerconfigjson: AgAK2ZWknLkScKTLfoU8+sushGHvDv4ryXOJOnWDit+ath3lgKJ7gWGL5nF4QMqwM8c4jbFjASPiM6lGwEA4xt2ZLbctCcSivpMDaM6z5qpQnuZIWS98dMdXaU3sfHzjbMYbWP5rjdN/dOVv/3Q1W5bvt0xE4jeC0wbJLVKQyKc5zGNnkpXAxmMsx3N66MHHJNIf1LeZNj5qntUGAACknyv6GBYiWxxxCMzcjeOvAKgmQ7qQ2L6Z91SEJAnRzQFXRgKZa9jWnE9VirbWnDneNjgqjOSH76vYy5BmvUtL4fLvagag2+6aRBL09KW999CozUKBHXsd3eCwHT0SKidZGK+4dXARZ/nYbHJmuV8dn+/pQJhhz7ugms9RwgqQBm3TtErj7WTrrGSig3Ym93sJBFCYdVMmrLHNF4+f87+nttb6k+vrmLYLYAoy3nbY9tmEvUEh9WasMpFi6W+r/gVuWswnQsUhLWbRwltXDXYJkwi+lMDfYGcpfPT3mum7mePXuYUQ2fglVuxyNkgIvMvPtHIZITUNtZGmP3OMxRCwcjZgrVZGOfcpDRM9bGHD5teMbsCPxQACEGFnUrrm0onmJQVcjJQMRYXy0oUZzPTKd12Bhh6dmWSzRgdlGnv9AdnnwmznHp+c+qXMu89fzHrQWm+c7iyMScVXcJBir0eOssO3Rjwl4AsJf6R/kxtjAOkfpJ+amdk+3iY4PSj+gjR8GBMxNSwJp19HCaYyhmk1Wu9ZSIWmd+hvKCmPGV24EBkuNoYflIK69FaOjuUbrkUTsRLz8k5rPcDWln4d8RlkFKxRHP6o/CIWT02nRUnF4HLs3NEiOMSFfDRZhxS47BmCrBqOmvdVtgRYx/AsTuChFp7xwLzG4f4pPBjpnUvAJB1gmbUYOgWrIBMS3AY7C0v/IQJo3l5UHq6Uj0S0DpXuC3gx9OUuTCdBt0cVWs9PzMInxVsfucdf9oxWBiEZmakhfm1WRnmKCC1ZEwkcVkAQijyG5x03bLdSWTGYLAHZWFkVvnKi1eFch7kiIDYAAahFg9Q0tSkL+0KdqbSsD9/DGq7tKdgRbnXRmyxG5KkV2QpbHJ9SS9zXMMacJz1dV1veP6/JNCz1eYIpdW5ryfxzO6q6P8239SoqXI4ENECSOgThpRbdIX/EJTIfClNbzmJlYPGBMThQdAw512YMO3jF0v6vDv5hO1JiC/5XkZPoOrqy/vJCMK10Z39RSk3BzYbNFDGzxZmbmw4OUpvaCWcHdzHD8Zhxc6ApR96kKJTgeMY3zI47RUO5f9j/rbn445k3g6yDWtOEcXDwj5Wlsuic3WwzIbj2UhZzlA2u8RpiqVSYPXO4
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      labels:
        created-by: pipeline
      name: ibm-entitlement-key
    type: kubernetes.io/dockerconfigjson

